### PR TITLE
fix: 修复$off的bug

### PR DESCRIPTION
**Pull request by igauch**
_event[event] => _events[event]

##### Checklist

- [x] `npm run test` passes
- [ ] tests and/or benchmarks are included
- [ ] cases or donate is changed or added
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/wepy?pullRequest=2415) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/wepy?pullRequest=2415) before we can accept your contribution.<br/><hr/>**tianwenjie** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/wepy?pullRequest=2415) it.</sub>

**Comment by dlhandsome** [comment]
感谢PR，还需要补充下 build dist 和 test case 哈

**Comment by igauch** [comment]
> 感谢 PR，还需要补充下 build dist 和 test case 哈

你们的build运行不起来啊，我看gulp是4.0版本，但gulpfile.js里的实现还是3版本的gulp.task("default", ["build"]);
并且npm run build并不能将core打包呢，请审查你们的本地代码，是不是没有同步上来，这很影响社区的贡献吧，谢谢

**Comment by dlhandsome** [comment]
可以通过 ```npm run dev:core``` 打包 dist，后续会把这些补充到贡献说明文档中去哈

**Comment by Gcaufy** [comment]
good catch~

**Pull request merged**
